import Head from 'next/head';
import Layout from '../components/layout';
import '../styles/sass/app.scss';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Codecademy Community</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default MyApp